# Generated by Django 4.1.6 on 2023-04-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plantPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantName', models.CharField(max_length=60)),
                ('latCoord', models.FloatField(max_length=10)),
                ('longCoord', models.FloatField(max_length=10)),
            ],
        ),
    ]
